### get all users
GET http://localhost:3000/auth/

### get user
GET http://localhost:3000/auth/3

### signup user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "ahmed13@gmail.com",
    "password": "123456"
}

### signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "ahmed1@gmail.com",
    "password": "123456"
}


### who am i
GET  http://localhost:3000/auth/whoami

### signout
POST http://localhost:3000/auth/signout

### delete user
DELETE http://localhost:3000/auth/7



### update user
PATCH  http://localhost:3000/auth/3
Content-Type: application/json

{
    "email": "ahmed_updated1@gmail.com"
}
